os: osx
osx_image: xcode11.1
language: swift
script: xcodebuild clean build test -workspace CleanMVVMSample.xcworkspace -scheme "CleanMVVMSample Staging" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.1,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)

